"""empty message

Revision ID: 11551aecc7cb
Revises: e25fdc9f1e69
Create Date: 2018-03-19 14:18:19.897102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11551aecc7cb'
down_revision = 'e25fdc9f1e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_hash', table_name='customers')
    op.create_index(op.f('ix_customers_hash'), 'customers', ['hash'], unique=True)
    op.create_unique_constraint(None, 'customers', ['id'])
    op.create_index(op.f('ix_openned_customer_hash'), 'openned', ['customer_hash'], unique=True)
    op.create_index(op.f('ix_openned_customer_id'), 'openned', ['customer_id'], unique=True)
    op.drop_index('customer_hash', table_name='openned')
    op.drop_index('customer_id', table_name='openned')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('customer_id', 'openned', ['customer_id'], unique=True)
    op.create_index('customer_hash', 'openned', ['customer_hash'], unique=True)
    op.drop_index(op.f('ix_openned_customer_id'), table_name='openned')
    op.drop_index(op.f('ix_openned_customer_hash'), table_name='openned')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_hash'), table_name='customers')
    op.create_index('ix_customers_hash', 'customers', ['hash'], unique=False)
    # ### end Alembic commands ###
