"""empty message

Revision ID: 60acdc8fdabf
Revises: f4a96ba971bb
Create Date: 2018-03-24 11:15:04.997107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60acdc8fdabf'
down_revision = 'f4a96ba971bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openned', sa.Column('client_phone', sa.String(length=21), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openned', 'client_phone')
    # ### end Alembic commands ###
