"""empty message

Revision ID: 89df3abcb08b
Revises: f451b6483432
Create Date: 2018-03-19 14:28:30.634600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89df3abcb08b'
down_revision = 'f451b6483432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_redirect_url', table_name='customers')
    op.drop_index('ix_customers_shorted_url', table_name='customers')
    op.create_foreign_key(None, 'openned', 'customers', ['customer_hash'], ['hash'])
    op.create_foreign_key(None, 'openned', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'openned', type_='foreignkey')
    op.drop_constraint(None, 'openned', type_='foreignkey')
    op.create_index('ix_customers_shorted_url', 'customers', ['shorted_url'], unique=False)
    op.create_index('ix_customers_redirect_url', 'customers', ['redirect_url'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    # ### end Alembic commands ###
