"""empty message

Revision ID: b9571035da71
Revises: ccb4b4d8038c
Create Date: 2018-03-22 10:17:44.609850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9571035da71'
down_revision = 'ccb4b4d8038c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openned', sa.Column('customer_ip', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openned', 'customer_ip')
    # ### end Alembic commands ###
