"""empty message

Revision ID: bbecd43563a1
Revises: 90a782e0753c
Create Date: 2018-03-23 22:44:56.639905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbecd43563a1'
down_revision = '90a782e0753c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_hash', sa.String(length=60), nullable=True),
    sa.Column('customer_ip', sa.String(length=30), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('ix_customers_hash', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_redirect_url', table_name='customers')
    op.drop_index('ix_customers_shorted_url', table_name='customers')
    op.create_unique_constraint(None, 'customers', ['hash'])
    op.create_unique_constraint(None, 'customers', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index('ix_customers_shorted_url', 'customers', ['shorted_url'], unique=False)
    op.create_index('ix_customers_redirect_url', 'customers', ['redirect_url'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_hash', 'customers', ['hash'], unique=False)
    op.drop_table('openned')
    # ### end Alembic commands ###
