"""empty message

Revision ID: bd040cc15bba
Revises: cd91d2fbff0e
Create Date: 2018-03-19 14:15:42.920129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd040cc15bba'
down_revision = 'cd91d2fbff0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_hash', sa.String(length=60), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_hash'], ['customers.hash'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('opened')
    op.drop_index('ix_customers_hash', table_name='customers')
    op.create_index(op.f('ix_customers_hash'), 'customers', ['hash'], unique=True)
    op.create_unique_constraint(None, 'customers', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_hash'), table_name='customers')
    op.create_index('ix_customers_hash', 'customers', ['hash'], unique=False)
    op.create_table('opened',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('customer_hash', mysql.VARCHAR(collation='utf8_polish_ci', length=60), nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_hash'], ['customers.hash'], name='opened_ibfk_1'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='opened_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_polish_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('openned')
    # ### end Alembic commands ###
