"""empty message

Revision ID: ccb4b4d8038c
Revises: 89df3abcb08b
Create Date: 2018-03-21 11:23:19.330075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb4b4d8038c'
down_revision = '89df3abcb08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('openned_ibfk_1', 'openned', type_='foreignkey')
    op.drop_constraint('openned_ibfk_2', 'openned', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('openned_ibfk_2', 'openned', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('openned_ibfk_1', 'openned', 'customers', ['customer_hash'], ['hash'])
    # ### end Alembic commands ###
