"""empty message

Revision ID: cd91d2fbff0e
Revises: 26f917576300
Create Date: 2018-03-19 13:46:37.362888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd91d2fbff0e'
down_revision = '26f917576300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_hash', table_name='customers')
    op.create_index(op.f('ix_customers_hash'), 'customers', ['hash'], unique=True)
    op.create_unique_constraint(None, 'customers', ['id'])
    op.add_column('opened', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('opened', sa.Column('open_time', sa.DateTime(), nullable=True))
    op.drop_column('opened', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opened', sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('opened', 'open_time')
    op.drop_column('opened', 'modified_time')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_hash'), table_name='customers')
    op.create_index('ix_customers_hash', 'customers', ['hash'], unique=False)
    # ### end Alembic commands ###
