"""empty message

Revision ID: ed09a3a6bcda
Revises: 
Create Date: 2018-03-19 12:56:40.817063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed09a3a6bcda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=21), nullable=True),
    sa.Column('redirect_url', sa.String(length=254), nullable=True),
    sa.Column('shorted_url', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_hash'), 'customers', ['hash'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_redirect_url'), 'customers', ['redirect_url'], unique=False)
    op.create_index(op.f('ix_customers_shorted_url'), 'customers', ['shorted_url'], unique=False)
    op.create_table('opened',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_hash', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_hash'], ['customers.hash'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opened')
    op.drop_index(op.f('ix_customers_shorted_url'), table_name='customers')
    op.drop_index(op.f('ix_customers_redirect_url'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_hash'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
