"""empty message

Revision ID: f451b6483432
Revises: f205d13cfa6d
Create Date: 2018-03-19 14:24:52.968310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f451b6483432'
down_revision = 'f205d13cfa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_hash', sa.String(length=60), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('ix_customers_hash', table_name='customers')
    op.create_index(op.f('ix_customers_hash'), 'customers', ['hash'], unique=True)
    op.create_unique_constraint(None, 'customers', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_hash'), table_name='customers')
    op.create_index('ix_customers_hash', 'customers', ['hash'], unique=False)
    op.drop_table('openned')
    # ### end Alembic commands ###
