"""empty message

Revision ID: f4a96ba971bb
Revises: bbecd43563a1
Create Date: 2018-03-24 11:08:41.263090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4a96ba971bb'
down_revision = 'bbecd43563a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=21), nullable=True),
    sa.Column('redirect_url', sa.String(length=254), nullable=True),
    sa.Column('shorted_url', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('hash', table_name='customers')
    op.drop_index('id', table_name='customers')
    op.drop_table('customers')
    op.add_column('openned', sa.Column('ga_client_id', sa.String(length=100), nullable=True))
    op.add_column('openned', sa.Column('ip', sa.String(length=30), nullable=True))
    op.add_column('openned', sa.Column('link_hash', sa.String(length=60), nullable=True))
    op.add_column('openned', sa.Column('link_id', sa.Integer(), nullable=True))
    op.drop_column('openned', 'customer_id')
    op.drop_column('openned', 'customer_hash')
    op.drop_column('openned', 'customer_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openned', sa.Column('customer_ip', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('openned', sa.Column('customer_hash', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('openned', sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('openned', 'link_id')
    op.drop_column('openned', 'link_hash')
    op.drop_column('openned', 'ip')
    op.drop_column('openned', 'ga_client_id')
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('hash', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=21), nullable=True),
    sa.Column('redirect_url', mysql.VARCHAR(length=254), nullable=True),
    sa.Column('shorted_url', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'customers', ['id'], unique=True)
    op.create_index('hash', 'customers', ['hash'], unique=True)
    op.drop_table('links')
    # ### end Alembic commands ###
